name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        mkdir .venv
        touch .venv/file.txt
        echo 1 > .venv/file.txt


    - name: Use Prime Numbers
      run: |
        pwd
        cat prime-numbers/file.txt